### ISSUE TITLE
Doesn't work with VPN enabled

### ISSUE THREAD

**Issue by mada199122** [mcarleio/my-jdownloader2-headless#7]
I've tried to run the image without the configuration of the VPN and it works fine...
If I place the config file and my credential in the environment parameter doesn't work.
From the log it seams that after the successful subscription to the vpn Jdownloader is no more able to connect to the web.

I've attached a log
[mcarleio-my-jdownloader2-headless1.html.zip](https://github.com/mcarleio/my-jdownloader2-headless/files/4348277/mcarleio-my-jdownloader2-headless1.html.zip)

**Comment by mcarleio** [comment]
Hi @mada199122,
sorry to here you have problems. Are you able to curl https://ifconfig.me/ from within the container? Please compare your OpenVPN file to this and check for differences: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/de596.nordvpn.com.udp.ovpn
Best regards
Marcel

**Comment by mada199122** [comment]
Hi Marcel,
I've abandoned and switch to an external container for the VPN connection
thanks

**Comment by mcarleio** [comment]
Ok, thanks for the info. Then I will close this issue.
